### ISSUE TITLE
Add sections on reproducing the book on the landing page

### ISSUE THREAD

**Issue by Robinlovelace** [geocompr/py#11]
One of the most important things for reproducibility and accessibility. Heads-up @anitagraser any suggestions on the local installation side v. welcome

- [x] Running the code locally (including python set-up instructions)
- [x] Running the code in Docker with IPython notebook (possibly the second most used approach)
- [ ] Running the code in Docker with VSCode
- [x] Running the code in Docker with RStudio
- [x] Running the code in Binder

**Comment by michaeldorman** [comment]
Added a preliminary version of local setup instructions, will be happy to hear any thoughts
https://github.com/geocompr/py/commit/dd90d990af0a2ffad9a62a1c2ea1721f02c2661f

**Comment by anitagraser** [comment]
The requirements.txt looks a bit overly specific

![image](https://user-images.githubusercontent.com/590385/156799087-7ee49c9a-6b2e-47e7-a069-37c430ca8b6e.png)

**Comment by Robinlovelace** [comment]
This basically done so will close : )
