### ISSUE TITLE
Error message in devcontainer

### ISSUE THREAD

**Issue by Robinlovelace** [geocompr/py#113]
Just hit this error:

```
File /opt/conda/envs/geocompy/lib/python3.10/site-packages/pandas/core/internals/base.py:70, in DataManager._validate_set_axis(self, axis, new_labels)
     67     pass
     69 elif new_len != old_len:
---> 70     raise ValueError(
     71         f"Length mismatch: Expected axis has {old_len} elements, new "
     72         f"values have {new_len} elements"
     73     )

ValueError: Length mismatch: Expected axis has 13 elements, new values have 11 elements
ValueError: Length mismatch: Expected axis has 13 elements, new values have 11 elements
```

Any ideas?

**Comment by Robinlovelace** [comment]
![image](https://user-images.githubusercontent.com/1825120/202473237-007b92e4-394f-4bdf-a1b4-af23ad76a726.png)

**Comment by Robinlovelace** [comment]
![image](https://user-images.githubusercontent.com/1825120/202476504-6d0a17d9-7975-4146-9c64-42d287280cb5.png)

**Comment by Robinlovelace** [comment]
![image](https://user-images.githubusercontent.com/1825120/202476780-ef81fa97-bfde-45d2-a905-535e55f9206c.png)

**Comment by Robinlovelace** [comment]
Update, this is the error message: 

```
Cell 36/48...

An error occurred while executing the following cell:
------------------
new_names =['i', 'n', 'c', 'r', 's', 't', 'a', 'p', 'l', 'gP', 'geom']
world2.columns = new_names
world2
------------------

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In [36], line 2
      1 new_names =['i', 'n', 'c', 'r', 's', 't', 'a', 'p', 'l', 'gP', 'geom']
----> 2 world2.columns = new_names
      3 world2

File /opt/conda/envs/geocompy/lib/python3.10/site-packages/geopandas/geodataframe.py:202, in GeoDataFrame.__setattr__(self, attr, val)
    200     object.__setattr__(self, attr, val)
    201 else:
--> 202     super().__setattr__(attr, val)

File /opt/conda/envs/geocompy/lib/python3.10/site-packages/pandas/core/generic.py:5915, in NDFrame.__setattr__(self, name, value)
   5913 try:
   5914     object.__getattribute__(self, name)
-> 5915     return object.__setattr__(self, name, value)
   5916 except AttributeError:
   5917     pass
```

Any ideas how to fix this?

**Comment by Robinlovelace** [comment]
I think it's a geopandas thing. Question for @martinfleis has anything changed upstream that could cause this, e.g. columns becoming sticky?

**Comment by Robinlovelace** [comment]
Failing lines:

https://github.com/geocompr/py/blob/390dcf17000721ce6700b7383dd05b665c2b311f/03-attribute-operations.qmd#L407-L409

**Comment by martinfleis** [comment]
@Robinlovelace do you have a full traceback? From the `Length mismatch: Expected axis has 13 elements, new values have 11 elements` it seems that the original df has 13 columns but you are passing a list of 11 only. 

When did this work last time? I am not aware of any change but could be.

**Comment by Robinlovelace** [comment]
The error is definitely fixed, many thanks Michael! Will look for the trace now Martin...

**Comment by Robinlovelace** [comment]
Heads-up @martinfleis finally reproduced the issue and have the full trace:

```
  Cell 36/48...ERROR: 

An error occurred while executing the following cell:
------------------
new_names = ['i', 'n', 'c', 'r', 's', 't', 'a', 'p', 'l', 'gP', 'geom'] 
world2.columns = new_names
world2
------------------

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In [36], line 2
      1 new_names = ['i', 'n', 'c', 'r', 's', 't', 'a', 'p', 'l', 'gP', 'geom'] 
----> 2 world2.columns = new_names
      3 world2

File /opt/conda/envs/geocompy/lib/python3.10/site-packages/geopandas/geodataframe.py:202, in GeoDataFrame.__setattr__(self, attr, val)
    200     object.__setattr__(self, attr, val)
    201 else:
--> 202     super().__setattr__(attr, val)

File /opt/conda/envs/geocompy/lib/python3.10/site-packages/pandas/core/generic.py:5915, in NDFrame.__setattr__(self, name, value)
   5913 try:
   5914     object.__getattribute__(self, name)
-> 5915     return object.__setattr__(self, name, value)
   5916 except AttributeError:
   5917     pass

File /opt/conda/envs/geocompy/lib/python3.10/site-packages/pandas/_libs/properties.pyx:69, in pandas._libs.properties.AxisProperty.__set__()

File /opt/conda/envs/geocompy/lib/python3.10/site-packages/pandas/core/generic.py:823, in NDFrame._set_axis(self, axis, labels)
    821 def _set_axis(self, axis: int, labels: AnyArrayLike | list) -> None:
    822     labels = ensure_index(labels)
--> 823     self._mgr.set_axis(axis, labels)
    824     self._clear_item_cache()

File /opt/conda/envs/geocompy/lib/python3.10/site-packages/pandas/core/internals/managers.py:227, in BaseBlockManager.set_axis(self, axis, new_labels)
    225 def set_axis(self, axis: int, new_labels: Index) -> None:
    226     # Caller is responsible for ensuring we have an Index object.
--> 227     self._validate_set_axis(axis, new_labels)
    228     self.axes[axis] = new_labels

File /opt/conda/envs/geocompy/lib/python3.10/site-packages/pandas/core/internals/base.py:70, in DataManager._validate_set_axis(self, axis, new_labels)
     67     pass
     69 elif new_len != old_len:
---> 70     raise ValueError(
     71         f"Length mismatch: Expected axis has {old_len} elements, new "
     72         f"values have {new_len} elements"
     73     )

ValueError: Length mismatch: Expected axis has 13 elements, new values have 11 elements
ValueError: Length mismatch: Expected axis has 13 elements, new values have 11 elements
```

**Comment by Robinlovelace** [comment]
Note: you can reproduce this in Codespaces: https://github.com/codespaces/new?hide_repo_select=true&ref=main&repo=447558863

**Comment by martinfleis** [comment]
@Robinlovelace is there an environment where the exact same code works?

**Comment by michaeldorman** [comment]
> Heads-up @martinfleis finally reproduced the issue and have the full trace:
> 
> ```
>   Cell 36/48...ERROR: 
> 
> An error occurred while executing the following cell:
> ------------------
> new_names = ['i', 'n', 'c', 'r', 's', 't', 'a', 'p', 'l', 'gP', 'geom'] 
> world2.columns = new_names
> world2
> ------------------
> 
> ---------------------------------------------------------------------------
> ValueError                                Traceback (most recent call last)
> Cell In [36], line 2
>       1 new_names = ['i', 'n', 'c', 'r', 's', 't', 'a', 'p', 'l', 'gP', 'geom'] 
> ----> 2 world2.columns = new_names
>       3 world2
> 
> File /opt/conda/envs/geocompy/lib/python3.10/site-packages/geopandas/geodataframe.py:202, in GeoDataFrame.__setattr__(self, attr, val)
>     200     object.__setattr__(self, attr, val)
>     201 else:
> --> 202     super().__setattr__(attr, val)
> 
> File /opt/conda/envs/geocompy/lib/python3.10/site-packages/pandas/core/generic.py:5915, in NDFrame.__setattr__(self, name, value)
>    5913 try:
>    5914     object.__getattribute__(self, name)
> -> 5915     return object.__setattr__(self, name, value)
>    5916 except AttributeError:
>    5917     pass
> 
> File /opt/conda/envs/geocompy/lib/python3.10/site-packages/pandas/_libs/properties.pyx:69, in pandas._libs.properties.AxisProperty.__set__()
> 
> File /opt/conda/envs/geocompy/lib/python3.10/site-packages/pandas/core/generic.py:823, in NDFrame._set_axis(self, axis, labels)
>     821 def _set_axis(self, axis: int, labels: AnyArrayLike | list) -> None:
>     822     labels = ensure_index(labels)
> --> 823     self._mgr.set_axis(axis, labels)
>     824     self._clear_item_cache()
> 
> File /opt/conda/envs/geocompy/lib/python3.10/site-packages/pandas/core/internals/managers.py:227, in BaseBlockManager.set_axis(self, axis, new_labels)
>     225 def set_axis(self, axis: int, new_labels: Index) -> None:
>     226     # Caller is responsible for ensuring we have an Index object.
> --> 227     self._validate_set_axis(axis, new_labels)
>     228     self.axes[axis] = new_labels
> 
> File /opt/conda/envs/geocompy/lib/python3.10/site-packages/pandas/core/internals/base.py:70, in DataManager._validate_set_axis(self, axis, new_labels)
>      67     pass
>      69 elif new_len != old_len:
> ---> 70     raise ValueError(
>      71         f"Length mismatch: Expected axis has {old_len} elements, new "
>      72         f"values have {new_len} elements"
>      73     )
> 
> ValueError: Length mismatch: Expected axis has 13 elements, new values have 11 elements
> ValueError: Length mismatch: Expected axis has 13 elements, new values have 11 elements
> ```

I'm seeing the old version of the code in the error message, the new version should work:
https://github.com/geocompr/py/blob/main/03-attribute-operations.qmd#L407

**Comment by Robinlovelace** [comment]
> @Robinlovelace is there an environment where the exact same code works?

Can you get into the environment here? https://github.com/codespaces/new?hide_repo_select=true&ref=main&repo=447558863

Can print out info from inside there if that would help. Thanks.

**Comment by Robinlovelace** [comment]
Sounds reasonable. I think there are environments in which the previous version of the code worked, that was my concern: it seems to be an intermittent undocumented bug/feature. Likely we can provide further info and examples of when the code worked/failed in different environments if that would help.
