### ISSUE TITLE
Every chapter starts with a description of the book, unhelpful

### ISSUE THREAD

**Issue by Robinlovelace** [geocompr/py#129]
E.g.: 

![image](https://user-images.githubusercontent.com/1825120/208326204-9bdb9d65-2fbf-49ca-896f-db0bef0c97e6.png)

**Comment by Robinlovelace** [comment]
Should be fixed in https://github.com/geocompr/py/pull/130

Not 100% sure. If anyone has an issue with that solution, delete the `description`, let me know.

**Comment by Robinlovelace** [comment]
If not, we can merge it asap.

**Comment by Nowosad** [comment]
Hi @Robinlovelace -- I think a better solution is to remove the description from the website template, and not from quarto. This way (I assume), it will still be visible for web searching, but not in the book:

https://github.com/geocompr/py/pull/131

**Comment by Robinlovelace** [comment]
OK, will merge and we'll find out!

**Comment by Nowosad** [comment]
![image](https://user-images.githubusercontent.com/3457131/208625272-d369ab9b-a5cc-41cc-be8a-ff5efd5bd8cf.png)
