### ISSUE TITLE
Build failing

### ISSUE THREAD

**Issue by Robinlovelace** [geocompr/py#13]
Since removing the landsat and 'air' datasets for #12 the build is failing : ( sorry!

I suggest we solve this by downloading the file if it does not exists, e.g. with:

```python
import subprocess
url = "https://github.com/geocompr/py/releases/download/0.1/landsat.tif"
path = "landsat.tif"
subprocess.run(["wget", "-r", "-nc", "-P", path, url])
```

**Comment by Robinlovelace** [comment]
Working on it and enjoying Quarto in VSCode.

![image](https://user-images.githubusercontent.com/1825120/156657034-8ae3e5a5-2920-47aa-81f2-74902add0f47.png)

**Comment by Robinlovelace** [comment]
```
ValueError                                Traceback (most recent call last)
~/orgs/geocompr/py/02-spatial-data.qmd in <module>
----> [345](file:///home/robin/orgs/geocompr/py/02-spatial-data.qmd?line=344)[ x = xr.open_dataset("data/air.2x2.250.mon.anom.comb.nc")

~/.local/lib/python3.8/site-packages/xarray/backends/api.py in open_dataset(filename_or_obj, engine, chunks, cache, decode_cf, mask_and_scale, decode_times, decode_timedelta, use_cftime, concat_characters, decode_coords, drop_variables, backend_kwargs, *args, **kwargs)
    477 
    478     if engine is None:
--> 479         engine = plugins.guess_engine(filename_or_obj)
    480 
    481     backend = plugins.get_backend(engine)

~/.local/lib/python3.8/site-packages/xarray/backends/plugins.py in guess_engine(store_spec)
    146         )
    147 
--> 148     raise ValueError(error_msg)
    149 
    150 

ValueError: did not find a match in any of xarray's currently installed IO backends ['scipy']. Consider explicitly selecting one of the installed engines via the ``engine`` parameter, or installing additional IO dependencies, see:
https://docs.xarray.dev/en/stable/getting-started-guide/installing.html
https://docs.xarray.dev/en/stable/user-guide/io.html]()
```

I got that error...

**Comment by michaeldorman** [comment]
> ```
> ValueError                                Traceback (most recent call last)
> ~/orgs/geocompr/py/02-spatial-data.qmd in <module>
> ----> [345](file:///home/robin/orgs/geocompr/py/02-spatial-data.qmd?line=344)[ x = xr.open_dataset("data/air.2x2.250.mon.anom.comb.nc")
> 
> ~/.local/lib/python3.8/site-packages/xarray/backends/api.py in open_dataset(filename_or_obj, engine, chunks, cache, decode_cf, mask_and_scale, decode_times, decode_timedelta, use_cftime, concat_characters, decode_coords, drop_variables, backend_kwargs, *args, **kwargs)
>     477 
>     478     if engine is None:
> --> 479         engine = plugins.guess_engine(filename_or_obj)
>     480 
>     481     backend = plugins.get_backend(engine)
> 
> ~/.local/lib/python3.8/site-packages/xarray/backends/plugins.py in guess_engine(store_spec)
>     146         )
>     147 
> --> 148     raise ValueError(error_msg)
>     149 
>     150 
> 
> ValueError: did not find a match in any of xarray's currently installed IO backends ['scipy']. Consider explicitly selecting one of the installed engines via the ``engine`` parameter, or installing additional IO dependencies, see:
> https://docs.xarray.dev/en/stable/getting-started-guide/installing.html
> https://docs.xarray.dev/en/stable/user-guide/io.html]()
> ```
> 
> I got that error...

According to this:
https://stackoverflow.com/questions/67725531/io-backend-error-in-the-axarray-for-netcdf-file
The issue is missing dependency `netCDF4`

**Comment by Robinlovelace** [comment]
Latest error on CI is related to `hvplot` not being installed. I will add it to the geocompr/geocompr:python image here https://github.com/geocompr/docker/blob/master/python/Dockerfile#L8


https://github.com/geocompr/py/runs/5431860037?check_suite_focus=true#step:4:74

**Comment by Robinlovelace** [comment]
Also... It just hangs for me when I try to reproduce this locally. I suspect this is linked to the download of the giant NetCDF file:

```
quarto preview
Preparing to preview
[1/9] 02-spatial-data.qmd

Starting Jupyter kernel...
```

**Comment by Robinlovelace** [comment]
This is fixed for now so closing.
