### ISSUE TITLE
GH pages issue in Chapters 5+

### ISSUE THREAD

**Issue by michaeldorman** [geocompr/py#133]
Chapters 5 and are not displayed in GH pages, while locally `quarto preview` works fine for me.

![Screenshot from 2022-12-20 16-20-42](https://user-images.githubusercontent.com/9386655/208688704-df65648a-98e6-4ccc-9672-59141840ee63.png)

The error is here:

```python
ValueError                                Traceback (most recent call last)
Cell In[34], line 1
----> 1 polygon = shapely.geometry.Polygon(list(multipoint.geoms))
      2 polygon

File /opt/conda/envs/geocompy/lib/python3.10/site-packages/shapely/geometry/polygon.py:251, in Polygon.__new__(self, shell, holes)
    246         return shapely.from_wkt("POLYGON EMPTY")
    248     if not np.issubdtype(shell.dtype, np.number):
    249         # conversion of coords to 2D array failed, this might be due
    250         # to inconsistent coordinate dimensionality
--> 251         raise ValueError("Inconsistent coordinate dimensionality")
    252 elif not isinstance(shell, LinearRing):
    253     shell = LinearRing(shell)

ValueError: Inconsistent coordinate dimensionality
ValueError: Inconsistent coordinate dimensionality
```

Was there a change in the Python version packages in GitHub actions? If so, how can I reproduce this environment? Thanks!

**Comment by Robinlovelace** [comment]
`docker pull geocompr/geocompr:mamba` and then open in VS Code and Devcontainer should do it, if that makes any sense?

**Comment by michaeldorman** [comment]
Got it, thanks @Robinlovelace !

Seems like this is related to the `shapely` upgrade to version `2.0.0`. At least for now solved using https://github.com/geocompr/py/commit/88a55b894d231d442c91ae1c3f34b90d398c3321 and now the book can be rendered.

However, we also need to remove the `pygeos` as encouraged in this message (after `import geopandas`):

```python
/tmp/ipykernel_788/388489786.py:2: UserWarning: Shapely 2.0 is installed, but because PyGEOS is also installed, GeoPandas will still use PyGEOS by default for now. To force to use and test Shapely 2.0, you have to set the environment variable USE_PYGEOS=0. You can do this before starting the Python process, or in your code before importing geopandas:

import os
os.environ['USE_PYGEOS'] = '0'
import geopandas

In a future release, GeoPandas will switch to using Shapely by default. If you are using PyGEOS directly (calling PyGEOS functions on geometries from GeoPandas), this will then stop working and you are encouraged to migrate from PyGEOS to Shapely 2.0 (https://shapely.readthedocs.io/en/latest/migration_pygeos.html).
  import geopandas as gpd
```

And further explained in the `shapely` docs: 
https://shapely.readthedocs.io/en/stable/migration_pygeos.html

I uninstalled `pygeos` from the dev container with `pip uninstall pygeos` which makes the warning go away, while the code still works. However I have no idea how to remove it from the remote(?) dev container, will be happy if you can please help with that.

**Comment by Robinlovelace** [comment]
Re pygeos, removing it in the env.yml and then updating the docker container may do it: https://github.com/geocompr/py/pull/134

**Comment by Robinlovelace** [comment]
Looking good: https://py.geocompx.org/06-raster-vector.html
