### ISSUE TITLE
Error in requirements.txt?

### ISSUE THREAD

**Issue by Robinlovelace** [geocompr/py#14]
Heads-up @michaeldorman I get the following:

```
pip install -r data/requirements.txt                     

ERROR: Invalid requirement: 'affine=2.3.0=py_0' (from line 4 of data/requirements.txt)
Hint: = is not a valid operator. Did you mean == ?
```

**Comment by michaeldorman** [comment]
Sorry, should have mentioned that this `requirements.txt` file is intended for `conda`. `pip` has its own structure (generated with `pip freeze > requirements.txt`. Please see attached example.
[requirements_pip.txt](https://github.com/geocompr/py/files/8183612/requirements_pip.txt)

**Comment by Robinlovelace** [comment]
Can we use that file when installing packages with pip? Guess so.
