### ISSUE TITLE
Update appendix

### ISSUE THREAD

**Issue by Robinlovelace** [geocompr/py#19]
I think this is a bit of an MVP before we put this out there: https://geocompr.github.io/py/a1-starting.html 

Reasoning: great that it's got installation instructions but it's for the wrong language (result of copying template from jjallaire)!

Happy to give this a bash but if anyone else has insight/experience into good practice when installing Python for geo work on Linux/Windows/Mac/Docker here's the place to say.

Key links: 

- The source code of the appendix (nice Quarto tricks in there): https://github.com/geocompr/py/edit/main/a1-starting.qmd
- Section on reproducing the book which has become a bit long, I suggest we move some of this into the appendix: https://geocompr.github.io/py/#reproducing-this-book

**Comment by michaeldorman** [comment]
The instructions look great, thanks @Robinlovelace !

**Comment by Robinlovelace** [comment]
Heads-up on this I now agree with @anitagraser that README is the best place to add install instructions. We could put the minimal instructions in the README and save the appendix for detailed IDE-specific instructions? On that note, ipynb version of c2 is looking good!

![image](https://user-images.githubusercontent.com/1825120/159184063-08708b9b-bc8b-4bd3-aaeb-ce484af0821b.png)

**Comment by michaeldorman** [comment]
> Heads-up on this I now agree with @anitagraser that README is the best place to add install instructions. We could put the minimal instructions in the README and save the appendix for detailed IDE-specific instructions? On that note, ipynb version of c2 is looking good!
> 
> ![image](https://user-images.githubusercontent.com/1825120/159184063-08708b9b-bc8b-4bd3-aaeb-ce484af0821b.png)

Yes, sounds good!
