### ISSUE TITLE
Set-up notes on Windows

### ISSUE THREAD

**Issue by Robinlovelace** [geocompr/py#22]
Making some notes here from recent installation experience.

- Installed Chocolatey
- Installed miniconda3
- Installed VS Code
- Installed the Quarto plugin in VS Code

At that point I tried running some Python code and was asked to select the Python Interpreter:

![image](https://user-images.githubusercontent.com/1825120/159127830-0cc242fc-e7f2-406f-b774-8f0c59d7e71e.png)

**Comment by Robinlovelace** [comment]
Happily it found the miniconda interpreter:

![image](https://user-images.githubusercontent.com/1825120/159127857-19965c9f-3794-4d2d-a5f0-01cb6468e7d9.png)

**Comment by Robinlovelace** [comment]
This is so variable per OS and with so many different options (including Quarto/Jupyter) I definitely think it deserves a decent section, in the Appendix #19 .

**Comment by Robinlovelace** [comment]
First time I tried to run some Python code I got this:

**Comment by Robinlovelace** [comment]
Unfortunately that failed? Any ideas Michael or Anita?? A bit confused, error message after clicking on message above suggests I'm in an infinite loop if I keep clicking Install!

![image](https://user-images.githubusercontent.com/1825120/159129529-aa4ce820-1dcf-4a21-ae3c-9fc0aafbc357.png)

**Comment by michaeldorman** [comment]
From my experience you need to open the Miniconda as administrator, and then:

```sh
conda install -c conda-forge ipykernel
```

Maybe the VScode button does this as ordinary non-administrator user, and that's why it's not working?

**Comment by Robinlovelace** [comment]
Will try. So far I've got...

```
(base) C:\Users\robinadmin\gh\geocompr\py>conda env create -f environment.yml
Collecting package metadata (repodata.json): failed

CondaError: KeyboardInterrupt

Terminate batch job (Y/N)?
```

**Comment by michaeldorman** [comment]
(Also, the `ipykernel` package should be included in the `requirements.txt` file which as part of the setup of all packages used in the book)

**Comment by michaeldorman** [comment]
> Will try. So far I've got...
> 
> ```
> (base) C:\Users\robinadmin\gh\geocompr\py>conda env create -f environment.yml
> Collecting package metadata (repodata.json): failed
> 
> CondaError: KeyboardInterrupt
> 
> Terminate batch job (Y/N)?
> ```

Interesting... I haven't tried creating environments yet

**Comment by Robinlovelace** [comment]
Things are happening...

![image](https://user-images.githubusercontent.com/1825120/159130004-add58864-b967-4f9f-b580-2ad3186dc26b.png)

**Comment by Robinlovelace** [comment]
Wow almost 20 minutes later and it's still not finished...

![image](https://user-images.githubusercontent.com/1825120/159130677-5880db5d-4dea-404f-aaf7-331184396d2f.png)

**Comment by michaeldorman** [comment]
I think it's normal, took a long time for me too

**Comment by Robinlovelace** [comment]
It's done 🎉  and gave me this helpfull message:

```
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate geocompy
#
# To deactivate an active environment, use
#
#     $ conda deactivate
```

**Comment by Robinlovelace** [comment]
You may need to set your environment to `geocompy` or another an environment with the necessary packages by clicking on the top right button in VS Code:

![image](https://user-images.githubusercontent.com/1825120/159131147-790489c7-3675-4536-b2b9-e2070ac27b1c.png)

**Comment by Robinlovelace** [comment]
One question: any idea how to change the default kernel/environment?

**Comment by Robinlovelace** [comment]
It's working but not sure what causes this message...

![image](https://user-images.githubusercontent.com/1825120/159131359-f66e42e5-bfbf-44a5-88c2-d3600fb6547e.png)

**Comment by michaeldorman** [comment]
> It's working but not sure what causes this message...
> 
> ![image](https://user-images.githubusercontent.com/1825120/159131359-f66e42e5-bfbf-44a5-88c2-d3600fb6547e.png)

This warning is always displayed when reading GPKG

**Comment by Robinlovelace** [comment]
> This warning is always displayed when reading GPKG

Any ideas why? See https://github.com/geopandas/geopandas/issues/2385 FYI

**Comment by michaeldorman** [comment]
> > This warning is always displayed when reading GPKG
> 
> Any ideas why? See [geopandas/geopandas#2385](https://github.com/geopandas/geopandas/issues/2385) FYI

There is an answer here, though can't say I understand it :-)
https://stackoverflow.com/questions/64995369/geopandas-warning-on-read-file

**Comment by anitagraser** [comment]
> Wow almost 20 minutes later and it's still not finished...

We could recommend mamba instead of conda. It's a much faster solver. https://mamba.readthedocs.io/

**Comment by Robinlovelace** [comment]
That sounds good to me, pls give it a bash if you get a chance.

**Comment by Robinlovelace** [comment]
Update on this here: 
![image](https://github.com/geocompx/geocompy/assets/1825120/10189f02-d146-41bc-83b0-76874c47246f)
