### ISSUE TITLE
Prevent more errors when data directory is not available

### ISSUE THREAD

**Issue by Robinlovelace** [geocompr/py#37]
Discovered this when testing out the new Binder instance

![image](https://user-images.githubusercontent.com/1825120/161346283-6d8bd4af-1495-4bfe-b237-e1e4e9da119e.png)

Suggested solution, something like this at the beginning of each chapter (we could also check if the `../data` directory exists):

https://github.com/geocompr/py/blob/50b2ba4b02be136ce86a23d03f0e02df79199604/02-spatial-data.qmd#L57-L69

**Comment by Robinlovelace** [comment]
Keen to hear thoughts on this before implementing solutions, many options...

**Comment by michaeldorman** [comment]
Sure, this is a great idea! (Download and extract data directory if not available)
We can add another check to see if it exists AND contains all data files, but not sure it's necessary because we can assume that if it exists then it came from the `data.zip` file downloaded earlier.

**Comment by anitagraser** [comment]
Isn't the issue here that in the qmds, the path `data/` is correct, while the ipynbs need `../data/`?

**Comment by Robinlovelace** [comment]
Yes. One option: put the ipynbs into the root directory. That would save a reasonable amount of hassle with the only negative being the 'neatness' of the repo. Thoughts?

**Comment by anitagraser** [comment]
Alternatively, we could first try `data/` and if it fails, try `../data/` and keep the repo clean.

**Comment by Robinlovelace** [comment]
> Alternatively, we could first try `data/` and if it fails, try `../data/` and keep the repo clean.

I'm pretty sure `../data` will work when running the `ipynb` files within the directory structure of this repo and on Binder. A reason I like the conditional 

```python
   r = requests.get("https://github.com/geocompr/py/releases/download/0.1/data.zip") 
   z = zipfile.ZipFile(io.BytesIO(r.content)) 
   z.extractall(".") 
```
code, however, is that it will work for someone who just downloads the .ipynb, .qmd or .py files.

**Comment by Robinlovelace** [comment]
That increases reproducibility I think.

**Comment by anitagraser** [comment]
Good. So the final solution should work in qmd and ipynb within the context of the full repo, as well as when a reader only downloads a single qmd/ipynb/py file.

**Comment by Robinlovelace** [comment]
Agreed, happy to work on this one (worth me creating a function to do that in one line?) but getting the build fixed is my priority..

**Comment by Robinlovelace** [comment]
Looking at this now...

**Comment by Robinlovelace** [comment]
This caused an issue with the build process, usefully picked up in changes for #76: https://github.com/geocompr/py/runs/7193848774?check_suite_focus=true#step:4:96
