### ISSUE TITLE
Making `landast.tif` avaiable to GitHub actions

### ISSUE THREAD

**Issue by michaeldorman** [geocompr/py#38]
I've added few more files to the (local) `data` directory, one of them (`landast.tif`) is large and in `.gitignore`, which makes the build fail. It's used in this example:

![Screenshot from 2022-04-02 01-14-03](https://user-images.githubusercontent.com/9386655/161348058-cbaed0cd-2efc-4766-bd6e-f0de46ff3203.png)

Will be happy to hear any ideas how we can make `landast.tif` available to GitHub actions. Thanks!

**Comment by Nowosad** [comment]
This file is here - https://github.com/Nowosad/spDataLarge/blob/master/inst/raster/landsat.tif. 
Maybe it could be downloaded in the GitHub action (https://github.com/Nowosad/spDataLarge/raw/master/inst/raster/landsat.tif)?

**Comment by Robinlovelace** [comment]
How about something like:

```python
 #| echo: false 
 from pathlib import Path 
 data_path = Path("data") 
 if data_path.is_dir(): 
   print("path exists") # directory exists 
 else: 
   print("Attempting to get and unzip the data") 
   import requests, zipfile, io 
   r = requests.get("https://github.com/geocompr/py/releases/download/0.1/data.zip") 
   z = zipfile.ZipFile(io.BytesIO(r.content)) 
   z.extractall(".") 
 ``` 

? 

I've given it a go here but not sure if that's ideal, or even if it will work, let's see if the tests pass 🤞  https://github.com/geocompr/py/pull/41

**Comment by michaeldorman** [comment]
Great, thanks @Robinlovelace and @Nowosad !
