### ISSUE TITLE
Code blocks not showing with correct run labels

### ISSUE THREAD

**Issue by Robinlovelace** [geocompr/py#40]
I think this was first mentioned by @michaeldorman and that I've found the cause. Reproducible example:

![image](https://user-images.githubusercontent.com/1825120/161369924-26ea7adc-9944-448e-b604-cdd2ed41ed93.png)

Solution described here: https://github.com/quarto-dev/quarto-vscode/issues/5

Add tags like this:

    ```{r}
    #| label: rtest

    ```

**Comment by Robinlovelace** [comment]
Is this still an issue @michaeldorman or anyone? Suspect we can close this...

**Comment by michaeldorman** [comment]
Sure, we can close this

**Comment by Robinlovelace** [comment]
Great, just testing VSCode + quarto chunks and working pretty well. Keen to hear of any more issues with quarto but if this is fixed we should close for sure. That's the assumption so closing for now!
