### ISSUE TITLE
GitHub actions error

### ISSUE THREAD

**Issue by michaeldorman** [geocompr/py#43]
The GitHub action produces an error as follows:

```text
 fatal: not in a git directory
Error: Process completed with exit code 128.
```

![Screenshot from 2022-05-08 10-50-53](https://user-images.githubusercontent.com/9386655/167286958-6e5efa84-b803-4804-88e8-40c63d9f1b7a.png)

However, the book is built nevertheless:

![Screenshot from 2022-05-08 10-50-10](https://user-images.githubusercontent.com/9386655/167286955-75d1b27e-36ef-462d-a3c6-caecfba60275.png)

**Comment by Robinlovelace** [comment]
That is odd, thanks for flagging Michael. Will take a look.

**Comment by michaeldorman** [comment]
Thanks!

**Comment by Robinlovelace** [comment]
Looks to be related: https://www.reddit.com/r/git/comments/85tolw/git_doesnt_recognize_my_local_repo_out_of_nowhere/

**Comment by Robinlovelace** [comment]
Now looking at this: https://stackoverflow.com/questions/71157844/how-can-i-copy-git-directory-to-the-container-with-github-actions

**Comment by Robinlovelace** [comment]
Debugging with this plugin: https://github.com/cschleiden/vscode-github-actions

**Comment by Robinlovelace** [comment]
Interesting, the commit above errors with this message, Git is installed but the folder is owned by a different user I think: 

```
Run git status
fatal: unsafe repository ('/__w/py/py' is owned by someone else)
To add an exception for this directory, call:

	git config --global --add safe.directory /__w/py/py
Error: Process completed with exit code 128.
```

**Comment by Robinlovelace** [comment]
Related issue: https://github.com/actions/checkout/issues/760

**Comment by Robinlovelace** [comment]
Finally the convert action is working. It was an epic mission! If we fix this we can fix anything, massive sigh of relief after 10+ test commits. Thanks @michaeldorman#2857 for amazing work on this https://github.com/geocompr/py/issues/43 

Also posted on Discord.

**Comment by michaeldorman** [comment]
Great, thanks @Robinlovelace !
