### ISSUE TITLE
Run convert action only when commit message contains a certain text string (convert)

### ISSUE THREAD

**Issue by Robinlovelace** [geocompr/py#44]
As documented here https://stackoverflow.com/questions/70377390/is-there-any-way-to-trigger-a-specific-github-action-workflow-by-commit-message you can make workflows run only when a certain key word is in the commit message. 

Thinking: we can use this to control when all the .py and .ipynb files are updated, after every commit is a bit much. Thoughts @anitagraser, @michaeldorman and @Nowosad ?

**Comment by Robinlovelace** [comment]
I think the commit above fixes it. If we merge #45 we should add the word 'convert' somewhere in the commit message if we want to rebuild the code, e.g. after making substantial changes to the Python code in one or more of the .qmd files.

**Comment by Nowosad** [comment]
Yes -- a good idea. Alternatively -- run it on a schedule.

**Comment by michaeldorman** [comment]
@Nowosad 's idea sounds good to me, perhaps there is a way to schedule every 24h?

**Comment by Robinlovelace** [comment]
We could get it to trigger every day/week (in case we forget, I'm not sure if it will update the code if no changes have been made, ideally not, any ideas?) *and* every time we mention `convert` in a commit. Best of both worlds?
