### ISSUE TITLE
Graph showing popularity of languages

### ISSUE THREAD

**Issue by Robinlovelace** [geocompr/py#5]
Inspired by https://geobgu.xyz/py/ by @michaeldorman  

Updated image from StackOverflow: 

![image](https://user-images.githubusercontent.com/1825120/154369626-0a45eb9c-4d19-4e48-9069-77c9f8e01e43.png)

Points: although Python is more popular overall, for data processing (roughly but not completely) captured by pandas questions, Python-for-data-science and R are more similar. I've thrown a few new ones in there, Rust is super future proof systems language (with low level geo crates in GeoRust), Julia is a new kid on the block with a similar focus as R.

**Comment by Robinlovelace** [comment]
https://insights.stackoverflow.com/trends?tags=r%2Cpandas%2Crust%2Cpython%2Cjulia

**Comment by michaeldorman** [comment]
Thanks, interesting! I'm not sure that the `pandas` tag captures everything related to data processing, for example image analysis, arrays, statistical methods, etc. may not be tagged with it. So perhaps there is even bigger advantage for Python than the figure shows.

**Comment by Robinlovelace** [comment]
Agreed, point is that popularity of Python for data analysis is somewhere between pandas and python lines, right?

**Comment by michaeldorman** [comment]
Yes, that would be my guess!

**Comment by kadyb** [comment]
Here are some other rankings on the popularity of programming languages, you might be interested:
1. RedMonk Programming Language Rankings: https://redmonk.com/sogrady/2022/03/28/language-rankings-1-22/
2. TIOBE Programming Community index: https://www.tiobe.com/tiobe-index/
3. PYPL PopularitY of Programming Language Index: https://pypl.github.io/PYPL.html

**Comment by Robinlovelace** [comment]
V. useful. The RedMonk one on rankings is interesting, lots of community activity for R

![image](https://user-images.githubusercontent.com/1825120/161310450-201a30ae-7a44-4cb6-948c-df27958cb729.png)

TIOBE gives a good indication of the direction of travel, both in the ascent: 

![image](https://user-images.githubusercontent.com/1825120/161310649-4291e475-ab66-4e13-bb23-9421b2079a6d.png)

Had never seen PYPL before, suggests upward trend of interest in R:

![image](https://user-images.githubusercontent.com/1825120/161310817-48987a69-7824-4646-88b4-7b62337c7d73.png)

**Comment by kadyb** [comment]
The PYPL index may be preferred over the TIOBE index (see the FAQ at the bottom of PYPL page). We can also create comparisons of the popularity of languages over time, just like in your first plot. 
![index](https://user-images.githubusercontent.com/35004826/161325538-dc97e211-31f5-4df2-818c-4bc85de4c0d7.png)

**Comment by Robinlovelace** [comment]
Closing as a bit out-of-scope for now.
