### ISSUE TITLE
Show graphical output side-by-side in first figure of Chapter 9

### ISSUE THREAD

**Issue by Robinlovelace** [geocompr/py#50]
Issue, these should be next to each other, not below each other: 

![image](https://user-images.githubusercontent.com/1825120/170866499-b53ff1c6-7e13-44be-aeb4-44d31f1bf100.png)

**Comment by Robinlovelace** [comment]
Working on a solution based on documentation here: https://quarto.org/docs/authoring/figures.html#computations

**Comment by Robinlovelace** [comment]
Let's see if it works... https://geocompr.github.io/py/09-mapping.html

**Comment by Robinlovelace** [comment]
Progress but seems to have duplicated the first figure:

![image](https://user-images.githubusercontent.com/1825120/170866935-6f605497-fe76-46c2-8698-6088006d2c81.png)

**Comment by Robinlovelace** [comment]
Strangely, it seems like the output is correct in the locally hosted version created with

```
quarto preview
```

![image](https://user-images.githubusercontent.com/1825120/170867203-b334397d-8c65-477d-b0d9-03d80a552f36.png)

**Comment by Robinlovelace** [comment]
Fixed. 
![image](https://user-images.githubusercontent.com/1825120/170867243-733f47ec-65f5-4529-8b1e-20207b3feca9.png)

**Comment by michaeldorman** [comment]
Nice! That's better and less confusing for the reader, than to write the multi-panel `matplotlib` code
