### ISSUE TITLE
Set-up Binder

### ISSUE THREAD

**Issue by Robinlovelace** [geocompr/py#6]
Ideally with Jupyter and RStudio options.

**Comment by Robinlovelace** [comment]
Progress on this: 
![image](https://user-images.githubusercontent.com/1825120/161339938-3c5960db-a266-4696-8d1c-130284448a83.png)

**Comment by Robinlovelace** [comment]
Source: https://mybinder.org/v2/gh/geocompr/py/main I think it just needs some tweaks to the Dockerfile in .binder now...

**Comment by Robinlovelace** [comment]
Interestingly, with now .binder folder that link works, it tries to install everything with mamba, let's see if it works!

![image](https://user-images.githubusercontent.com/1825120/161341059-50e5ad8a-f7f0-4ef7-b610-737a94f8330c.png)

**Comment by Robinlovelace** [comment]
Great news, it works!

![image](https://user-images.githubusercontent.com/1825120/161342864-27f995d7-7ca1-4ea2-8a09-ce3023f9b20c.png)

Now just need to add the badge and think it's job done on this. Binder support out-of-the-box is a nice thing about the Python world.

**Comment by michaeldorman** [comment]
Nice!

**Comment by Robinlovelace** [comment]
![Peek 2022-05-29 14-48](https://user-images.githubusercontent.com/1825120/170872360-5962da0a-27da-4a44-b164-8bb315132d0e.gif)
