### ISSUE TITLE
Chapters not displayed on GitHub pages

### ISSUE THREAD

**Issue by michaeldorman** [geocompr/py#66]
Pages other than `index.html` return error 404 at the moment, not sure why. For example:
https://geocompr.github.io/py/02-spatial-data.html
![Screenshot from 2022-07-02 00-27-23](https://user-images.githubusercontent.com/9386655/176969876-e1f0b3ce-8eac-42ae-a36b-656aca5d7805.png)

**Comment by Robinlovelace** [comment]
That is unexpected, well spotted! It must have been these changes, but not sure how: https://github.com/geocompr/py/pull/61/files. My plan: revert those changes to at least get the build working again and then maybe revisit... I'll also take a look at the logs in Actions for any clues...

**Comment by Robinlovelace** [comment]
Update, you can see the html files representing the chapters being removed with commands such as `rm 02*.html` here: https://github.com/geocompr/py/runs/7157573424?check_suite_focus=true#step:5:53

**Comment by Robinlovelace** [comment]
Actions now failing : ( https://github.com/geocompr/py/runs/7158854116?check_suite_focus=true Plan B: try to deploy directly to netlify, that will also help keep the commit history clean and the repo small.

**Comment by michaeldorman** [comment]
> Actions now failing : ( https://github.com/geocompr/py/runs/7158854116?check_suite_focus=true Plan B: try to deploy directly to netlify, that will also help keep the commit history clean and the repo small.

Thanks @Robinlovelace !

**Comment by michaeldorman** [comment]
Right now GitHub pages isn't working once again

**Comment by Robinlovelace** [comment]
Also affects the Netlify deploy: https://vocal-longma-0d407b.netlify.app/02-spatial-data.html is there but not the other chapters.

**Comment by Robinlovelace** [comment]
This is the culprit: https://github.com/geocompr/py/commit/8bf4f111628b41ad6b028d75522d5a5bb6acebb8 

Seems that the switch to the conda image caused the other chapters to fail silently.

**Comment by Robinlovelace** [comment]
Cause: no nbformat or jupyter packages.

Source: https://github.com/geocompr/py/runs/7152659812?check_suite_focus=true#step:4:16

**Comment by Robinlovelace** [comment]
> Cause: no nbformat or jupyter packages.

However, this issue has been fixed. This is the latest error message:

```
  Cell 30/40...
An error occurred while executing the following cell:
------------------
names = sorted(world.columns, reverse=True)
world2 = worlds[names]
world2
------------------
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
Input In [30], in <cell line: 2>()
      1 names =sorted(world.columns, reverse=True)
----> 2 world2 =worlds[names]
      3 world2
NameError: name 'worlds' is not defined
```

Source

https://github.com/geocompr/py/runs/7192401135?check_suite_focus=true#step:4:115

**Comment by Robinlovelace** [comment]
This is the culprit I think: 

https://github.com/geocompr/py/blob/d733dc8ddcf178369b9b8587cd6cb11c30f7a3ad/03-attribute-operations.qmd#L306

**Comment by Robinlovelace** [comment]
Broader issues: GitHub Actions should notify us when things like this happen.

**Comment by michaeldorman** [comment]
> This is the culprit I think:
> 
> https://github.com/geocompr/py/blob/d733dc8ddcf178369b9b8587cd6cb11c30f7a3ad/03-attribute-operations.qmd#L306

Thanks @Robinlovelace !
