### ISSUE TITLE
Test interactive plots

### ISSUE THREAD

**Issue by Robinlovelace** [geocompr/py#7]
Do they work in Quarto. Worth switching to ipynb format?

**Comment by Robinlovelace** [comment]
Just came across that looks really promising: https://github.com/giswqs/leafmap thoughts @anitagraser ?

**Comment by anitagraser** [comment]
> Leafmap is built upon several open-source packages, such as [folium](https://github.com/python-visualization/folium) and [ipyleaflet](https://github.com/jupyter-widgets/ipyleaflet) (for creating interactive maps),

I haven't tested Leafmap yet but if Folium works in Quarto, so might Leafmap.

**Comment by anitagraser** [comment]
Good news: hvplot with bokeh backend looks fine

![vscode-quarto-hvplot](https://user-images.githubusercontent.com/590385/156789486-6ec0c440-ba0a-4130-a6cc-80c3921c88ed.gif)

**Comment by Robinlovelace** [comment]
:tada: so cool!

**Comment by Robinlovelace** [comment]
And as of now in the online version :tada: 

![Peek 2022-03-06 20-15](https://user-images.githubusercontent.com/1825120/156940571-cf182212-29da-4fde-9d72-9943ea8332c0.gif)

Truth be told I'm not that impressed: main benefit of interactive maps is context and base layers. I think this example is worth keeping but should we move it to the vis chapter? Currently it's here: https://geocompr.github.io/py/02-spatial-data.html#vector-data

**Comment by anitagraser** [comment]
Great. Base layers are easy to add. I don't agree re main benefit. In my experience, few dataset viz are helpful if you cannot zoom in to see details.

**Comment by Robinlovelace** [comment]
Yeah being able to zoom is a huge benefit and great you can end based layers. However, the UI of the bokeh-based interactive map didn't feel as natural as other interactive maps I've tried. Look forward to testing results from folium and maybe leafmap and more.

**Comment by Robinlovelace** [comment]
Update on this, interactive tiles looking good, finally got round to having a look: https://github.com/geopandas/geopandas/issues/2385

**Comment by Robinlovelace** [comment]
Tested, they work, closing for now, can always open another issue on specifics.
