### ISSUE TITLE
Operations on data and Geometry in GeoPandas and Shapely

### ISSUE THREAD

**Issue by anisotropi4** [geocompr/py#72]
Having more or less completed the NaPTAN PR I have been having a look at the other chapters which look very good.

They did pose a question about how to keep consistency with the PR or example:

1. Reading CSV data files from a file, buffer or data either in `Pandas` (.read_csv) or memory (.from_dict)
2. Extracting dataframe columns to `numpy` array, and handling issues around `numpy` array shape
3. Creating `GeoSeries` geometry from a 2-d `numpy` using `.from_xy`
4. Using `Shapely` binary predicates to identify geometric relationships, for example `.within` with a `GeoSeries`

There are then other interesting predicate functions such as `.contains`, `.crosses` and so on.

**Comment by michaeldorman** [comment]
Excellent questions and suggestions, thanks @anisotropi4 ! 
1. This is an essential part, in the current draft we don't have that. (@Robinlovelace - Is it in the parts of "geocompr" which we haven't covered yet, or it's not there at all?)
2. This probably belongs in https://geocompr.github.io/py/03-attribute-operations.html, but we need to think of an example that can't be done with `pandas` alone.
3. We have it (incidentally) in the "spatial join" section (https://geocompr.github.io/py/04-spatial-operations.html#spatial-joining). I agree it should be explained separately. (again, perhaps it's in the parts not completed yet?)
4. We have the `geopandas` versions of those, for example in https://geocompr.github.io/py/04-spatial-operations.html#topological-relations.

**Comment by anisotropi4** [comment]
Based on the discussion above I've added a few examples to chapter 03. Hope this works.

**Comment by anisotropi4** [comment]
I'm going to close this as I think this is now done.
