### ISSUE TITLE
Use of an explicit index paradigm

### ISSUE THREAD

**Issue by anisotropi4** [geocompr/py#73]
Please would you consider the following approach in the introductory chapters of introducing an example of using an index to filter dataframes so that rather than writing

```
df[df['A'] == 3]
```

I would create an variable `idx` to hold the boolean filter

```
idx = df['A'] == 3
df[idx]
```

This has the advantage when the filter becomes more complex, it makes it clearer what the intent is. For example when using the `~` ($not$) operation.

Then then working with multiple filters makes using the `&` and `|`  (logical and and or) more straightforward.

For example I feel the intent of following examples is somewhat clearer:

```
idx1 = df['A'] == 3
idx2 = df['B'] == 'Q'

df[~idx1]
df[idx1 & ~idx2]
```

Rather than

```
df[~(df['A'] == 3)]
df[(df['A'] == 3) & ~df['B'] == 'Q']
```

**Comment by michaeldorman** [comment]
> Please would you consider the following approach in the introductory chapters of introducing an example of using an index to filter dataframes so that rather than writing
> 
> ```
> df[df['A'] == 3]
> ```
> 
> I would create an variable `idx` to hold the boolean filter
> 
> ```
> idx = df['A'] == 3
> df[idx]
> ```
> 
> This has the advantage when the filter becomes more complex, it makes it clearer what the intent is. For example when using the `~` (not) operation.
> 
> Then then working with multiple filters makes using the `&` and `|` (logical and and or) more straightforward.
> 
> For example I feel the intent of following examples is somewhat clearer:
> 
> ```
> idx1 = df['A'] == 3
> idx2 = df['B'] == 'Q'
> 
> df[~idx1]
> df[idx1 & ~idx2]
> ```
> 
> Rather than
> 
> ```
> df[~(df['A'] == 3)]
> df[(df['A'] == 3) & ~df['B'] == 'Q']
> ```

Definitely! I agree it's better

**Comment by Robinlovelace** [comment]
Great, is this fixed now the relevant PR is merged? Sorry not keeping up with all the changes!

**Comment by anisotropi4** [comment]
This is working and the "worlds"->"world" bug was fixed, and I now have got a `quarto` tool-chain working on my local machine.

**Comment by Robinlovelace** [comment]
Great, I think this is done so closing for now.
