### ISSUE TITLE
Add action to identify failing lines of code

### ISSUE THREAD

**Issue by Robinlovelace** [geocompr/py#76]
Split-out from #66 and linked to #71.

**Comment by Robinlovelace** [comment]
I think it's now working, it identified the fact that the .ipynb files would fail due to data not being in the expected place, linking to #37. Source: https://github.com/geocompr/py/runs/7193848774?check_suite_focus=true#step:4:96

**Comment by Robinlovelace** [comment]
It's now failing, but for the right reason I think!

https://github.com/geocompr/py/runs/7194282696?check_suite_focus=true

**Comment by Robinlovelace** [comment]
Heads-up @anisotropi4 I've tried to get this going and think we may be close but am now seeing this issue: https://github.com/geocompr/py/runs/7194439044?check_suite_focus=true#step:4:69

Any ideas what the cause is and how to fix it? It's a new level of reproducibility testing all the standalone .ipynb files!

**Comment by michaeldorman** [comment]
> Heads-up @anisotropi4 I've tried to get this going and think we may be close but am now seeing this issue: https://github.com/geocompr/py/runs/7194439044?check_suite_focus=true#step:4:69
> 
> Any ideas what the cause is and how to fix it? It's a new level of reproducibility testing all the standalone .ipynb files!

Sorry, this is something added today - the caption apparently cannot contain `:` (at least not as is). Trying to fix it now.

**Comment by michaeldorman** [comment]
> 

Good idea!
