### ISSUE TITLE
Basic example of raster data in visualisation chapter

### ISSUE THREAD

**Issue by Robinlovelace** [geocompr/py#83]
Working on this, starting with the following:

![image](https://user-images.githubusercontent.com/1825120/185890062-4ed420bb-021c-40b8-a7ae-36fe77d6d2d0.png)

**Comment by Robinlovelace** [comment]
My thinking on this: transform the nz_elev object into the same CRS as the nz object. Sound reasonable @michaeldorman ?

**Comment by Robinlovelace** [comment]
Code underlying this:

```
import matplotlib as mpl
from matplotlib import pyplot
import geopandas as gpd
import rasterio
import rasterio.plot
nz = gpd.read_file("data/nz.gpkg")
```

## Static maps

- Focus on matlibplot
- First example: NZ with fill and borders
- Scary matplotlib code here...

```{python}
#| layout-ncol: 3
nz.plot(color="grey");
nz.plot(color="none", edgecolor="blue");
nz.plot(color="grey", edgecolor="blue");
```



As covered in Chapter 2, you can plot raster datasets as follows:

```{python}
nz_elev = rasterio.open('data/nz_elev.tif')
nz_elev_read = nz_elev.read(1)
pyplot.imshow(nz_elev_read);
```





You can combine the raster and vector plotting methods shown above into a single visualisation with multiple layers as follows:



```{python}
fig, ax = pyplot.subplots(figsize=(15, 15))
rasterio.plot.show(nz_elev_read, ax=ax);
nz_transformed.plot(ax=ax, facecolor='blue', edgecolor='r');
```

**Comment by Robinlovelace** [comment]
Working on this but no success. Any ideas @anitagraser or @michaeldorman ? Seems like it should be working to me... Asking people at FOSS4G in person also.

https://github.com/geocompr/py/blob/20167b08a8845dd015515f62de984d3fdbcda067/09-mapping.qmd#L94-L105

**Comment by Robinlovelace** [comment]
Update: this is the latest reproducible example that I would expect to work:

```
nz_transformed = gpd.read_file('https://github.com/geocompr/py/releases/download/0.1/nz_transformed.gpkg')

# Plot nz_transformed
nz_transformed.plot(facecolor='none', edgecolor='r'); # works

# Plot nz_elev:
rasterio.plot.show(nz_elev_read);

# Plot combined
fig, ax = pyplot.subplots(figsize=(15, 15))
rasterio.plot.show(nz_elev_read, ax=ax);
nz_transformed.plot(ax=ax, facecolor='none', edgecolor='r'); # fails

```

**Comment by michaeldorman** [comment]
> My thinking on this: transform the nz_elev object into the same CRS as the nz object. Sound reasonable @michaeldorman ?

Thanks, I think the other way around, transform the vector layer to the CRS of the raster, is that what you had in mind?

**Comment by Robinlovelace** [comment]
> Thanks, I think the other way around, transform the vector layer to the CRS of the raster, is that what you had in mind?

Yes I had that in mind and attempted it but it seemed not to work...

**Comment by michaeldorman** [comment]
I think it works now, I used `.to_crs` to transform `nz`:

```python
fig, ax = plt.subplots(figsize=(5, 5))
rasterio.plot.show(nz_elev, ax=ax)
nz.to_crs(nz_elev.crs).plot(ax=ax, facecolor='none', edgecolor='r');
```

**Comment by Robinlovelace** [comment]
Looks good to me Michael, feel free to change the example I've added to the vis chapter, learning in progress!

**Comment by Robinlovelace** [comment]
Update: I've checked the website and this is better IMO:

![image](https://user-images.githubusercontent.com/1825120/186263873-f00245b0-03c6-46fd-a53e-407f0f315e67.png)

Great work, I've learned at least one thing today!

Source: https://geocompr.github.io/py/09-mapping.html

In fact addition of raster under vector borders early in the vis chapter is something we can learn from in Geocomputation with R, although not a priority atm.
