### ISSUE TITLE
Better instructions on using Docker

### ISSUE THREAD

**Issue by Robinlovelace** [geocompr/py#87]
Currently there's no Docker section in the README. This reflects the need for better Docker support (including on geocompr/docker) also but we should at least document a reproducible workflow in Docker. What I would love to have is VSCode in a Docker image, any ideas on that v. welcome so help wanted!

**Comment by Robinlovelace** [comment]
Hi @jsta yes it would be great having the wonderful VS Code available out-of-the box, with the hand quarto plugin pre-installed if poss. Is that asking too much? Happy to chat this over, many thanks for getting involved, love how open source projects work!

**Comment by jsta** [comment]
Is it mostly getting VS Code and GUI forwarding added to this image? https://github.com/geocompr/docker/blob/master/conda/Dockerfile

**Comment by Robinlovelace** [comment]
> Is it mostly getting VS Code and GUI forwarding added to this image? https://github.com/geocompr/docker/blob/master/conda/Dockerfile

Yes exactly :100:

**Comment by jsta** [comment]
From shell:
`docker run --rm -it geocompr/geocompr:conda`

From VSCode:
Open Docker extension tab
Right-click the running container -> Attach Visual Studio Code

Now, I can run `quarto convert`.

Then if I install the quarto and python extensions "inside" the container and select the geocompr(conda) Python interpreter,
I can scroll through individual qmd files and run the chunks.

**Comment by Robinlovelace** [comment]
Thanks so much for the demo @jsta, sounds like this is a documentation issue in that case!

**Comment by Robinlovelace** [comment]
Interestingly, no data files. Guess I will need something like:

```
docker run --rm -it -v ($pwd):/home/py
```

To get the local version of the files in the remote 'devcontainer'? In any case this is v. cool!

![image](https://user-images.githubusercontent.com/1825120/192889403-cdcf8e34-ed46-4264-a139-5ef4304b1584.png)

**Comment by Robinlovelace** [comment]
Thinking now: would be good to add a devcontainer.json: https://code.visualstudio.com/docs/remote/containers

**Comment by Robinlovelace** [comment]
OK I see now that when I open a file from inside `code`, e.g. with `code -r 02*` it opens it in the container. Awesome!

![image](https://user-images.githubusercontent.com/1825120/192891573-55d93c94-266f-4c25-b48c-99328e65029f.png)

**Comment by Robinlovelace** [comment]
This now seems a lot simpler.

![image](https://user-images.githubusercontent.com/1825120/202933928-eb6de086-f9a5-43cd-9932-e6ec84746d45.png)
