### ISSUE TITLE
Input datasets

### ISSUE THREAD

**Issue by Robinlovelace** [geocompr/py#9]
To go into releases if over 1MB.

**Comment by michaeldorman** [comment]
The only big sample data file (also the only one not from the R book) is the NetCDF file at ~100 MB. 

https://github.com/geocompr/py/blob/main/data/air.2x2.250.mon.anom.comb.nc

I'll try to find a smaller NetCDF file, will be happy to hear if you have any suggestion

**Comment by michaeldorman** [comment]
What do you think about replacing the ~100MB NetCDF file with the <1MB on from here?
https://crudata.uea.ac.uk/cru/data//temperature/absolute_v5.nc
If the file is small, I guess we can keep it in the `data` directory on GitHub, and it would be easier for readers not to deal with file download and `subprocess` in the main text...
Will be happy to hear your thoughts, thanks!

**Comment by Robinlovelace** [comment]
> What do you think about replacing the ~100MB NetCDF file with the <1MB on from here?

Great idea, big thumbs up from me :+1:

**Comment by michaeldorman** [comment]
Great! https://github.com/geocompr/py/commit/b50f5749e5a3d2aa7d2376c24b74f016df1f8ee7

**Comment by Robinlovelace** [comment]
I think this issue can be closed for now??

**Comment by Robinlovelace** [comment]
We can always reopen...
