### ISSUE TITLE
"Reproducing this book" manual method

### ISSUE THREAD

**Issue by michaeldorman** [geocompr/py#95]
"Reproducing this book" section (in the index page) should perhaps include instructions for those willing to reproduce the book locally, without using quarto but just to run the `ipynb` files:
1. Link to download the data
2. Link to download the `.ipynb` files
3. List of packages that need to be installed for this to work
Will be happy to hear your thoughts, thanks!

**Comment by Robinlovelace** [comment]
:+1: from me on this idea

**Comment by Robinlovelace** [comment]
I think there is a possibility of duplication of information between README.md and index.qmd. I think it's a good idea to have reproducing the book in the index, as that's the main place people will look. There's also the appendix #19.

**Comment by michaeldorman** [comment]
Thanks @Robinlovelace ! 

I'm not sure how can we include a downloadable ZIP with the data and another one with the `ipynb` files in the GitHub publishing framework. Will be happy for help with this.

In my courses I'm using a static server and just place the ZIP file inside the served directory, updated each time the book is rendered, for example:
```sh
#!/bin/bash
Rscript -e 'rmarkdown::render_site(encoding="UTF-8")'
cd _book/examples/ && zip -r -FS ../examples.zip * && cd ../../
```

**Comment by Robinlovelace** [comment]
> I'm not sure how can we include a downloadable ZIP with the data and another one with the `ipynb` files in the GitHub publishing framework. Will be happy for help with this.

Releases are the way. This contains the always-up-to-date .ipynb files https://github.com/geocompr/py/archive/refs/heads/main.zip and we could set-up a script to generate releases containing the data also.

**Comment by michaeldorman** [comment]
Great, thanks!

**Comment by michaeldorman** [comment]
https://github.com/geocompr/py/pull/102
