### ISSUE TITLE
Example of creating vector layers and rasters from scratch

### ISSUE THREAD

**Issue by michaeldorman** [geocompr/py#96]
I suggest adding two sections on creating vector layers and rasters from scratch:
1. For vector layers, I didn't locate an existing example in the R book (please correct me if I'm wrong). There are examples of creating geometries (https://geocompr.github.io/py/02-spatial-data.html#geometries) but not all the way to a `GeoDataFrame`.
2. For rasters, there is an example here: https://geocompr.robinlovelace.net/attr.html#vector-attribute-aggregation, however I think it should belong in a standalone section titled "creating raster from scratch" because it requires explaining specific concepts about the `rasterio` raster model

I suggest including examples similar to these:
1. https://geobgu.xyz/py/geopandas1.html#creating-from-scratch
2. https://geobgu.xyz/py/rasterio1.html#creating-raster-from-array

Will be happy to hear what you think, and if we do add this content where do you think is the right place for it in the book

**Comment by Nowosad** [comment]
@michaeldorman You have an R/vector example at https://geocompr.robinlovelace.net/spatial-class.html#sf

**Comment by michaeldorman** [comment]
> @michaeldorman You have an R/vector example at https://geocompr.robinlovelace.net/spatial-class.html#sf

Thanks, I missed that! Will add an example like this in Ch 2, and another corresponding one for rasters

**Comment by michaeldorman** [comment]
https://github.com/geocompr/py/pull/103
